# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technicareasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jeamaJoal vs. Automation 
email: jeamajoal@gmail.com
description: "Beginning the day I found the NIBBLES.BAS file on my dad's computer as a 6th grader and realized i could change the game by modifying the text, I was hooked. Now, being in IT since the early 2000s, I have automated a lot of things. Some for fun, alot for work, and now some for security.  Join me as i share some of my work as I use my experiences to fuel content for this blog."
#twitter_username: username
github_username: jeamajoal
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "jeamaJoal"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Multi-decade IT engineer pivoting focus to security and red teaming, leveraging a rich history of innovation for the challenges ahead."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "X (formerly Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jeamajoal/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeamajoal"
#    - label: "Instagram"
 #     icon: "fab fa-fw fa-instagram"
  #    url: "https://instagram.com/"

footer:
  links:
    - label: "X (formerly Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jeamajoal"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeamajoal"
 #   - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
   #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
